### ISSUE TITLE
invalid use of template-name 'RH_RF95' without an argument list

### ISSUE THREAD

**Issue by ECEquentin** [Seeed-Studio/Grove_LoRa_433MHz_and_915MHz_RF#4]
I dont understand why but the "rf95_reliable_datagram_server" exemple, give me this error at the compilation IDE arduino :

Arduino : 1.8.9 (Windows 10), Carte : "Arduino Nano, ATmega328P"

rf95_reliable_datagram_server:38:1: error: invalid use of template-name 'RH_RF95' without an argument list

 RH_RF95 driver;

 ^

exit status 1
invalid use of template-name 'RH_RF95' without an argument list

**Comment by 16mhz8bit** [comment]
Did you figure it out?

**Comment by ackPeng** [comment]
@ECEquentin Do you still have this question now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
