### ISSUE TITLE
communicating with ESP32 Lora + Lora Library

### ISSUE THREAD

**Issue by gavan-x** [Seeed-Studio/Grove_LoRa_433MHz_and_915MHz_RF#5]
currently have the rf95_client sending with

` rf95.setFrequency(868.0);`

and ESP32 Lora receivers using Lora library, but not reading any data.

Is the data sent via   `rf95.send(data, sizeof(data)); ` readable by other lora receivers with the same chip  SX1276 using the Lora library and not the RH_RF95?

if the 2 libraries are not compatible. ( RH_RF95 & Lora ).
it would be helpful for a simple client example of the grove module using the Lora library.

Thank you.

**Comment by ackPeng** [comment]
@gavan1 Have you solved this problem?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
