### ISSUE TITLE
Add library version 2.0.0 to Arduino Library Manager

### ISSUE THREAD

**Issue by philippewarren** [Seeed-Studio/Grove_LoRa_433MHz_and_915MHz_RF#6]
The version 2.0.0 of the library can't be installed from the Arduino Library Manager.
The required steps should be taken to allow it to be installed from the Arduino Library Manager.

**Comment by ackPeng** [comment]
Thank you very much, we will explore how to install it

**Comment by Lesords** [comment]
Sorry, I've been busy lately.

I have updated the library version and republished the release.

It takes a day for the Arduino library manager to take effect.

**Comment by Lesords** [comment]
I'm going to close this issue, feel free to re-open it if you have any other questions.
